version: '3.8'

services:
  postgres:
    image: postgres
    container_name: reading-recommender
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MHMDessam
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:MHMDessam@postgres:5432/postgres
    volumes:
      - .:/app

volumes:
  pgdata:
